# Generated by Django 3.2.4 on 2021-07-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(verbose_name='last time fetched')),
                ('username', models.CharField(max_length=200)),
                ('xml_data', models.TextField()),
            ],
        ),
    ]
